### ISSUE TITLE
Issue with Dark GitHub themes

### ISSUE THREAD

**Issue by Vangelis66** [Vallek/vallek-github-custom-css#1]
Many thanks for this GH userstyle 👍 !
It appears it's now down to the community to try and fix this new Microsoft 😡 abomination...

While your userstyle apparently works as designed with GH **light themes**, e.g. 

![GHLT](https://github.com/Vallek/vallek-github-custom-css/assets/9669492/fdf8d66f-5c55-41b8-82ad-0db3b96562d6)

... it has issues with dark themes, e.g. 

![GHDS](https://github.com/Vallek/vallek-github-custom-css/assets/9669492/f48d4f7f-b82d-4c9a-8d79-d38fdc54d0e9)

As I hope you can see and reproduce, the selected/focused tab (in this example, `<> Code`) stays **white** over a dark background, with its borders and text obscured 😭 ; also, in the default dark theme, a selected tab has an "underline", e.g. 

![underline](https://github.com/Vallek/vallek-github-custom-css/assets/9669492/f0be12cd-6679-43a0-864c-04e1c35ec5a2)

How do you plan to deal with that? Can you keep it but colour it, e.g., dark blue (or enable such a configuration inside the user.css) ?

Many thanks! 😄

**Comment by Vallek** [comment]
Hey! Thanks for report! I forgot to test it with dark theme at all)

Yeah it shouldn't be a big problem (famous last words), i shall fix it. I'll close this when it's done.

**Comment by Vallek** [comment]
Hey on a unrelated note: do you know why numbers on your tabs are so stretched? I don't see it on my end (chrome and firefox, win10).

**Comment by Vallek** [comment]
Fixed. Please report any new problems with dark theme in new issues.

**Comment by Vangelis66** [comment]
> do you know why numbers on your tabs are so stretched?

Yes I do, in fact 😜 ; nothing you should worry about yourself, though 😄 !

The browser used is called **Serpent 52** and is very popular among the retrocomputing communities; the browser does not yet support `CSS min()/max()` that is used by Microsoft to render borders; more about it, if you care, [here](https://msfn.org/board/topic/184051-my-browser-builds-part-4/?do=findComment&comment=1254110) ...

People on Windows XP/Vista 32-bit can't use the latest Chrome/Firefox, but other browsers are still available for them; the thing is Microsoft and Google constantly break them by **implementing the latest draft versions of Javascript and CSS,** in their quest to render unusable **anything** (OS, browser engine) dating more than half a year ago 😞 ; but this is off-topic here, obviously 😜 ...

Kindest regards.

**Comment by Vangelis66** [comment]
> Fixed

Can confirm 🎉 : 

![GHDTfix](https://github.com/Vallek/vallek-github-custom-css/assets/9669492/2413f429-503d-4a53-9eeb-9893acc95c78)

Focused tab _isn't being themed_ by the third party dark theme called [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark), but this is probably not your fault (though I'd appreciate a fix, if you can come up with one 😉 ) : 

![GHDTfix-GD](https://github.com/Vallek/vallek-github-custom-css/assets/9669492/02a4dcd3-26c5-4bee-b0ad-07a51ad8329d)

Thanks again for your prompt actions! ❤️

**Comment by Vallek** [comment]
>The browser used is called Serpent 52

It never ceases to amaze me how many different browsers and customizations are out there)) I'm glad that fix worked for you cause it uses relatively new 'prefers-color-scheme'. 

>third party dark theme called [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark)

Well idk maybe if it uses same css variables as Github. But I didn't use them here cause time, lazy etc.) I might look into it to make my style more universal but no promises.

You are welcome and thanks!

**Comment by Vangelis66** [comment]
> It never ceases to amaze me how many different browsers ... are out there

... Truth be told, this is NOT the case in 2023 😢 ; ALL the major brands, including MS's latest Edge, are **Chromium**/Webkit under the hood; **Mozilla Firefox**, the only other mainstream browser engine (Gecko), is mostly a chase-after-Chrome's-butt 😃 Chromium wannabe...

> cause it uses relatively new 'prefers-color-scheme'.

Yes indeed, _that_ is supported by **Serpent 52** 👍 ...

> I might look into it to make my style more universal but no promises.

I totally understand, take your time...

Thanks again, best wishes!

**Comment by Vallek** [comment]
I added GitHub-Dark support but only when dark theme activated. Would appreciate a test)

upd And now it should work with both settings!
